Compiled from "OnErrorNotImplementedException.java"
public final class io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException extends java.lang.RuntimeException {
  private static final long serialVersionUID;

  public io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException(java.lang.String, java.lang.Throwable);
    Code:
       0: aload_0
       1: aload_1
       2: aload_2
       3: ifnull        10
       6: aload_2
       7: goto          17
      10: new           #1                  // class java/lang/NullPointerException
      13: dup
      14: invokespecial #2                  // Method java/lang/NullPointerException."<init>":()V
      17: invokespecial #3                  // Method java/lang/RuntimeException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
      20: return

  public io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException(java.lang.Throwable);
    Code:
       0: aload_0
       1: new           #4                  // class java/lang/StringBuilder
       4: dup
       5: invokespecial #5                  // Method java/lang/StringBuilder."<init>":()V
       8: ldc           #6                  // String The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling |
      10: invokevirtual #7                  // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
      13: aload_1
      14: invokevirtual #8                  // Method java/lang/StringBuilder.append:(Ljava/lang/Object;)Ljava/lang/StringBuilder;
      17: invokevirtual #9                  // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
      20: aload_1
      21: invokespecial #10                 // Method "<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
      24: return
}
